# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: CT Test
description: Builds the library with given flags and runs Valgrind-based constant-time tests

inputs:
  cflags:
    description: CFLAGS to pass to compilation
    default: ""
  valgrind_flags:
    description: Extra flags to pass to valgrind
    default: ""

runs:
  using: composite
  steps:
      - name: System info
        shell: ${{ env.SHELL }}
        run: |
          ARCH=$(uname -m)
          echo <<-EOF
            ## Setup
            Architecture: $ARCH
            - $(uname -a)
            - $(nix --version || echo 'nix not present')
            - $(bash --version | grep -m1 "")
            - $(python3 --version)
            - $(${{ inputs.cross_prefix }}${CC} --version | grep -m1 "")
          EOF
          cat >> $GITHUB_STEP_SUMMARY <<-EOF
            ## Setup
            Architecture: $ARCH
            - $(uname -a)
            - $(nix --version || echo 'nix not present')
            - $(bash --version | grep -m1 "")
            - $(python3 --version)
            - $(${{ inputs.cross_prefix }}${CC} --version | grep -m1 "")
          EOF
      - shell: ${{ env.SHELL }}
        run: |
          make clean
          # Disable the AArch64 SHA3 extension as it's not yet supported by valgrind
          MK_COMPILER_SUPPORTS_SHA3=0 tests func --exec-wrapper="valgrind --error-exitcode=1 --track-origins=yes ${{ inputs.valgrind_flags }}" --cflags="-DMLK_CONFIG_CT_TESTING_ENABLED -DNTESTS_FUNC=50 ${{ inputs.cflags }}"
