# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Lint-Markdown
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint-markdown-link:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # v1.0.17
